import Game from './game/Game'
import './styles/game.css'
import './styles/desktop.css'
import './styles/windows.css'
import './styles/map.css'
import './styles/fixes.css'
import './styles/publishing.css'
import './styles/facility.css'
import './styles/dispatch.css'
import './styles/apps.css'
import './styles/finance.css'
import './styles/economy.css'
import './styles/market.css'
import './styles/progression.css'
import './styles/route-planning.css'
import './styles/incidents.css'
import './styles/landmarks.css'
import './styles/goals.css'
import './styles/hito7.css'
import './styles/story.css'
import './styles/onboarding.css'
import './styles/polish.css'
import './styles/mobile.css'

export default function App() {
  return <Game />
}
